### ISSUE TITLE
Google camera crashes on image capture and Nokia 7 plus default camera shows error

### ISSUE THREAD

**Issue by Ehtisham95** [jrvansuita/PickImage#117]
After I capture image on my Nokia 7 plus. It shows an error saying "There was a problem saving your photo or video". **This happened after I updated my phone to Android 10**. On Android 9 (pie) it worked fine. on my Google Pixel XL (android 10) the Google Camera app crashes after I capture the photo.
This is the image on Nokia 7 plus.
![1578564526143](https://user-images.githubusercontent.com/24632786/72058550-17bda380-32f2-11ea-9a76-7a3bd43467eb.JPEG)
On Google Pixel it displays ANR saying **"Camera has stopped working."** 
In my Log: it says:
```
 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.GoogleCamera, PID: 28939
    java.lang.IllegalArgumentException: Could not open output uri for writing
        at enp.m(PG:54)
        at enj.onShutterButtonClick(PG:8)
        at keg.onShutterButtonClick(PG:4)
        at com.google.android.apps.camera.ui.shutterbutton.ShutterButton.performClick(PG:208)
        at android.view.View.performClickInternal(View.java:7117)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27351)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.io.FileNotFoundException: open failed: EACCES (Permission denied)
        at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:149)
        at android.content.ContentProviderProxy.openAssetFile(ContentProviderNative.java:631)
        at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1521)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1338)
        at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1286)
        at oqy.b(PG:65)
        at enp.m(PG:52)
        at enj.onShutterButtonClick(PG:8) 
        at keg.onShutterButtonClick(PG:4) 
        at com.google.android.apps.camera.ui.shutterbutton.ShutterButton.performClick(PG:208) 
        at android.view.View.performClickInternal(View.java:7117) 
        at android.view.View.access$3500(View.java:801) 
        at android.view.View$PerformClick.run(View.java:27351) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by Ehtisham95** [comment]
I have found a solution. It is due to Scope Storage feature of Android 10. 
In short, Scope Storage prevents apps from having unrestricted access to the file system on the device. Previously, an app could access any file on the device using the standard File APIs, and it only needed the user to grant the storage permission.
To resolve the issue:
Assuming your target SDK version is Android 10 or higher `(targetSdkVersion >= 29)`, set the value of `requestLegacyExternalStorage` to `true` in your app's manifest file:
```
<manifest ... >
    <!-- This attribute is "false" by default on apps targeting
         Android 10 or higher. -->
    <application android:requestLegacyExternalStorage="true" ... >
      ...
    </application>
</manifest>
```
