### ISSUE TITLE
crash if there is not picker application

### ISSUE THREAD

**Issue by yogeshpaliyal** [jrvansuita/PickImage#129]
Crash if I select to pick from the gallery and there is no App supported Action.PICK

**Comment by build3r** [comment]
@ProMode7 
Might need a similar fix for camera too
```
Fatal Exception: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 pkg=android clip={text/uri-list U:content://*****.vansuita.pickimage.provider/camera_pics/***/20201231_230014.jpg} (has extras) }
       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1951)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1621)
       at android.app.Activity.startActivityForResult(Activity.java:4593)
       at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:675)
       at androidx.core.app.ActivityCompat.startActivityForResult(ActivityCompat.java:234)
       at androidx.fragment.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:795)
       at androidx.fragment.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:932)
       at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1278)
       at androidx.fragment.app.Fragment.startActivityForResult(Fragment.java:1266)
       at com.vansuita.pickimage.resolver.IntentResolver.launchCamera(IntentResolver.java:101)
       at com.vansuita.pickimage.dialog.PickImageBaseDialog.launchCamera(PickImageBaseDialog.java:255)
       at com.vansuita.pickimage.dialog.PickImageDialog.onCameraClick(PickImageDialog.java:66)
       at com.vansuita.pickimage.dialog.PickImageBaseDialog$1.onClick(PickImageBaseDialog.java:189)
       at android.view.View.performClick(View.java:6325)
       at android.view.View$PerformClick.run(View.java:25114)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:192)
       at android.app.ActivityThread.main(ActivityThread.java:6759)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:875)
       ```
