### ISSUE TITLE
TransactionTooLargeException: data parcel size

### ISSUE THREAD

**Issue by msnainps** [jrvansuita/PickImage#161]
App crash after opening the camera. Getting this log in logcat.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.perceptive.Instadispatch.driver, PID: 17925
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2977664 bytes
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3776)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)
     Caused by: android.os.TransactionTooLargeException: data parcel size 2977664 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:615)
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3700)
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3768)

**Comment by majedalmoqbeli** [comment]
I got the same issue.
Did you fix it? @msnainps

**Comment by msnainps** [comment]
@majedalmoqbeli , No I used some third-party library but issue is still there in old code

**Comment by majedalmoqbeli** [comment]
@msnainps what is the new library do you use?

**Comment by msnainps** [comment]
https://github.com/jrvansuita/PickImage

**Comment by majedalmoqbeli** [comment]
This is the same library that you open this issue on it!!!!!
