### ISSUE TITLE
App crash after take a photo using camera [ java.lang.IllegalArgumentException ]

### ISSUE THREAD

**Issue by majedalmoqbeli** [jrvansuita/PickImage#163]
Hi @jrvansuita ,
App crash after take a photo using camera. This crash happened in most of user they using my app, The common between all these devices is that the language and numbers are Arabic.

**I think the issue because the name of image is with Arabic numbers** 
like this : `٢٠٢٣٠٣٢٩_٢٣٢٢٤٤.jpg
`
**below is the error log:**
```
Fatal Exception: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/2AC7-1F05/Android/data/com.test_myapp/files/Pictures/MYAP/٢٠٢٣٠٣٢٩_٢٣٢٢٤٤.jpg
       at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:2)
       at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:3)
       at com.vansuita.pickimage.resolver.IntentResolver.cameraUriForProvider(IntentResolver.java:3)
       at com.vansuita.pickimage.resolver.IntentResolver.getCameraIntent(IntentResolver.java:2)
       at com.vansuita.pickimage.resolver.IntentResolver.launchSystemChooser(IntentResolver.java:6)
       at com.vansuita.pickimage.dialog.PickImageBaseDialog.launchSystemDialog(PickImageBaseDialog.java:2)
       at com.vansuita.pickimage.dialog.PickImageBaseDialog.onCreateView(PickImageBaseDialog.java:13)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:19)
       at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:6)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:6)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:8)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:84)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:4)
       at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:3)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:101)
       at android.os.Looper.loop(Looper.java:166)
       at android.app.ActivityThread.main(ActivityThread.java:7529)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

```

Thanks..

**Comment by majedalmoqbeli** [comment]
Hi,

I thing that if you add the  `Locale.ENGLISH` will fix this.
 [In this line](https://github.com/jrvansuita/PickImage/blob/dbdfaf88128973afa3b1e2b4d1888d178af43155/library/src/main/java/com/vansuita/pickimage/resolver/IntentResolver.java#L126)
to be like below:
`String timeStamp = new SimpleDateFormat("yyyyMMdd_HHmmss", Locale.ENGLISH).format(new Date());`

Thanks..

**Comment by majedalmoqbeli** [comment]
Hi Bro @jrvansuita, I did the change and send pull request please accept. thanks a lot.

**Comment by jrvansuita** [comment]
[![](https://jitpack.io/v/jrvansuita/PickImage.svg)](https://jitpack.io/#jrvansuita/PickImage)
