### ISSUE TITLE
Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by sayah-y** [jrvansuita/PickImage#20]
Hello,

I use the library in a fragment. When I open the camera and I click back. I have this error:

`
E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: ileo.eurowatt.fiqsit, PID: 6170
                                                 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=196609, result=0, data=Intent {  }} to activity {ileo.eurowatt.fiqsit/ileo.eurowatt.fiqsit.ui.activity.NCSaveActivity}: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3574)
                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                  Caused by: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
                                                     at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
                                                     at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
                                                     at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:649)
                                                     at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
                                                     at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:205)
                                                     at android.support.v4.app.DialogFragment.dismiss(DialogFragment.java:171)
                                                     at com.vansuita.pickimage.PickImageDialog.onActivityResult(PickImageDialog.java:214)
                                                     at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
                                                     at android.app.Activity.dispatchActivityResult(Activity.java:6192)
                                                     at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
                                                     at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617) 
                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:151) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:135) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
`

I think that you need to change `dismiss();` with `dismissAllowingStateLoss();` in the onActivityResult of PickerDialog.

Thanks for your work.

**Comment by jrvansuita** [comment]
Ok, fixed. Changed to` dismissAllowingStateLoss()`, can you check for me if is it working?

**Comment by sayah-y** [comment]
Hello,

Thanks for your work :)

I see your commit but It seems that in the release v2.0.8, sources don't change. I have always `dismiss()`. So, the issue is always here. It's strange !
I try a `full-clean` with Gradle and `invalidate cache and restart` in Android studio. But no change.

I did a screenshot:

<img width="930" alt="capture d ecran 2017-02-21 a 11 17 18" src="https://cloud.githubusercontent.com/assets/2410393/23160694/b348a89e-f827-11e6-89f9-4e448337a721.png">

Thanks !

**Comment by sayah-y** [comment]
I just download the zip of the v2.0.8.

And I have always :


```
@Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == IntentResolver.REQUESTER) {
            if (resultCode == RESULT_OK) {
                //Show progress
                showProgress(true);

                //Handle the image result async
                getAsyncResult().execute(data);
            } else {
                dismiss();
            }
        }
    }
```

So, there is an error.

Thanks a lot !

**Comment by jrvansuita** [comment]
Yeap, my mistake. Try it with 2.0.9!

**Comment by sayah-y** [comment]
Good news, the issue is fixed ;)

Thanks :)

**Comment by qadir227** [comment]
how to resolve this? I am getting it too. Should I have to edit the PickImageDialog.java library file for myself?, do I need to update the library?
I have installed the library as per docs here https://github.com/jrvansuita/PickImage#setup

**Comment by jrvansuita** [comment]
@qadir227 You need to update the library version.
