### ISSUE TITLE
Activity destroyed

### ISSUE THREAD

**Issue by sayah-y** [jrvansuita/PickImage#23]
Hello @jrvansuita ,

Sometimes the app has low memory before the pick intent (camera or gallery).
So, activity is destroyed. 
Does the library manage this situation ?
It seems that I have this issue sometimes.

Thanks.

**Comment by jrvansuita** [comment]
Hi @sayah-y, the answer is no, the library doesn't handle this situation. One time a got this bug and tried to implement that. But never more I got it, so I let the bug. Can you help me to fix this?

**Comment by GuilhE** [comment]
Having the same problem:

d.app.ActivityThread$H.handleMessage(ActivityThread.java:1537)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:207)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
Caused by java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1842)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1860)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:650)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:609)
       at android.support.v4.app.DialogFragment.show(DialogFragment.java:143)
       at com.vansuita.pickimage.dialog.PickImageDialog.show(PickImageDialog.java:56)
       at com.vansuita.pickimage.dialog.PickImageDialog.show(PickImageDialog.java:52)

**Comment by jrvansuita** [comment]
Yeap, @GuilhE can you help me to solve this issue? I'm completely out of time to fix this now.

**Comment by GuilhE** [comment]
@jrvansuita Let me see what I can do.

**Comment by GuilhE** [comment]
I haven't noticed your lib provides permission logic, which it's cool. I was managing it with Dexter and after being granted permission I was calling this:
```

if (!mActivity.isFinishing() && callback != null) {
            PickImageDialog.build(
                    new PickSetup()...
                    .show(mActivity);
```

And it was failing in some devices. I'm not using Dexter to check Camera permissions now, and it's working. Later, with more time and patience I'll give it a second try and see if it's something in your code or not.

**Comment by jrvansuita** [comment]
Hi, any news about it?

**Comment by GuilhE** [comment]
Not yet, I had to move on with the project. 
The use case, If you want to test it, is to request permissions with Dexter instead of your lib. Inside the success callback add: `PickImageDialog.build...show(activity)`.

**Comment by jairobjunior** [comment]
I am having the same problem of the activity being destroyed. It is 100% reproducible when you enable the option "Don't keep activities" from dev options.

I haven't had time to go though the code, but it sounds like a field not being saved, maybe on the `onSaveInstanceState`.
