### ISSUE TITLE
App crashes on clicking the pick image button

### ISSUE THREAD

**Issue by surbhitrao** [jrvansuita/PickImage#39]
java.lang.NoSuchFieldError: com.vansuita.pickimage.R$id.card
                                                                                            at com.vansuita.pickimage.dialog.PickImageBaseDialog.onBindViewsHolders(PickImageBaseDialog.java:136)
                                                                                            at com.vansuita.pickimage.dialog.PickImageBaseDialog.onCreateView(PickImageBaseDialog.java:72)
                                                                                            at android.support.v4.app.Fragment.performCreateView(Fragment.java:2192)
                                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
                                                                                            at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                                            at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                                            at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                                            at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                                            at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                                            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                                            at android.os.Handler.handleCallback(Handler.java:733)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                            at android.os.Looper.loop(Looper.java:136)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:5045)
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                                            at dalvik.system.NativeStart.main(Native Method)

**Comment by jrvansuita** [comment]
Not here, are you sure? Can you paste here your piece of code?
