### ISSUE TITLE
Crash when accepting permissions

### ISSUE THREAD

**Issue by porkyhead** [jrvansuita/PickImage#58]
Using version 2.1.5 on Android 8.1. Target SDK = 25, Compile SDK = 26.

On a fresh app install:
- Pick camera
- Accept permissions
- Crash

`java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=65635, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.app.happenings.beta/com.app.happenings.ui.profile.CreateProfileActivity}: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Pictures/Happ DEV/20180118_140656.jpg
                                                                             at android.app.ActivityThread.deliverResults(ActivityThread.java:4268)
                                                                             at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312)
                                                                             at android.app.ActivityThread.-wrap19(Unknown Source:0)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                             at android.os.Looper.loop(Looper.java:164)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                          Caused by: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Pictures/Happ DEV/20180118_140656.jpg
                                                                             at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:719)
                                                                             at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:404)
                                                                             at com.vansuita.pickimage.resolver.IntentResolver.cameraUriForProvider(IntentResolver.java:139)
                                                                             at com.vansuita.pickimage.resolver.IntentResolver.getCameraIntent(IntentResolver.java:74)
                                                                             at com.vansuita.pickimage.resolver.IntentResolver.launchCamera(IntentResolver.java:83)
                                                                             at com.vansuita.pickimage.dialog.PickImageBaseDialog.launchCamera(PickImageBaseDialog.java:230)
                                                                             at com.vansuita.pickimage.dialog.PickImageDialog.onRequestPermissionsResult(PickImageDialog.java:112)
                                                                             at android.support.v4.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:785)
                                                                             at com.app.happenings.ui.profile.CreateProfileActivity.onRequestPermissionsResult(CreateProfileActivity.java:159)
                                                                             at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7419)
                                                                             at android.app.Activity.dispatchActivityResult(Activity.java:7270)
                                                                             at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
                                                                             at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312) 
                                                                             at android.app.ActivityThread.-wrap19(Unknown Source:0) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                             at android.os.Looper.loop(Looper.java:164) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:6494) 
                                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                                             at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) `

**Comment by jrvansuita** [comment]
Make a pull request and fix it. I would be great to see some contribution.
