### ISSUE TITLE
App Crash when i choose camera

### ISSUE THREAD

**Issue by AmineNac** [jrvansuita/PickImage#71]
the app crash when i choose camera on android 5.1 (Lolipop) but works fine on newer versions of Android.
here is the exception thrown: 

04-20 14:53:19.362 7409-7409/com.example.hp.mycasa E/UncaughtException: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/sdcard1/Pictures/MyCasa/20180420_145319.jpg
        at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:738)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:417)
        at com.vansuita.pickimage.resolver.IntentResolver.cameraUriForProvider(IntentResolver.java:143)
        at com.vansuita.pickimage.resolver.IntentResolver.getCameraIntent(IntentResolver.java:78)
        at com.vansuita.pickimage.resolver.IntentResolver.launchCamera(IntentResolver.java:87)
        at com.vansuita.pickimage.dialog.PickImageBaseDialog.launchCamera(PickImageBaseDialog.java:233)
        at com.vansuita.pickimage.dialog.PickImageDialog.onCameraClick(PickImageDialog.java:64)
        at com.vansuita.pickimage.dialog.PickImageBaseDialog$1.onClick(PickImageBaseDialog.java:167)
        at android.view.View.performClick(View.java:4848)
        at android.view.View$PerformClick.run(View.java:20270)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5660)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)

**Comment by suriyadi15** [comment]
Same error for me

**Comment by chandakmayank** [comment]
Same issue for me
