### ISSUE TITLE
App crash on grant permission 

### ISSUE THREAD

**Issue by hims9391** [jrvansuita/PickImage#83]
E/UncaughtException: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=65635, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.example.www.cms/com.example.www.abc.Activity.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4126)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4169)
        at android.app.ActivityThread.-wrap20(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6186)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=1; index=-1
        at com.vansuita.pickimage.dialog.PickImageDialog.onRequestPermissionsResult(PickImageDialog.java:121)
        at android.support.v4.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:804)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7089)
        at android.app.Activity.dispatchActivityResult(Activity.java:6941)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4122)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4169) 
        at android.app.ActivityThread.-wrap20(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6186) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by AmitTurner** [comment]
having the same problem.

**Comment by hims9391** [comment]
is this file updated in 2.1.9 version??

**Comment by AmitTurner** [comment]
Yes, there's a mistype there.

**Comment by hims9391** [comment]
how to update that file or wait for new update?

**Comment by AmitTurner** [comment]
I had a problem updating locally as our Gradle collide, so just sync version 2.1.5 (the one worked for me anyway) and the mistype is not there. Until it will be fixed it's a temp solution.

**Comment by hims9391** [comment]
i will try..hope it completely executed..very thank u.#AmitTurner

**Comment by YuriAR** [comment]
Same issue. Using version 2.1.5 didn't work.

**Comment by steam0111** [comment]
I had the same problem and I just updated library version and now I don't have that problem

**Comment by jrvansuita** [comment]
Already Fixed.

**Comment by chetakbhimani001** [comment]
May I know the latest version?
